parameters:
  jaxon:
    app:
      directories:
        '%kernel.project_dir%/jaxon/App':
          namespace: \Jaxon\App
          # separator: '' # '.' or '_'
          # protected: []
      packages:
        Lagdo\DbAdmin\Package:
          template: bootstrap4
          servers:
            mysql:
              name: MySQL
              driver: mysql
              host: localhost
              port: 3306
              username: invoice
              password: t27M9RpaJmd45Twz
              access:
                # server: true
                databases:
                  - voyager
                  - adminer
                  - crater
                  - invoice
                  - demo
            pgsql:
              name: PostgreSQL
              driver: pgsql
              host: 127.0.0.1
              port: 5432
              username: postgres
              password:
              access:
                # server: true
                databases:
                  - voyager
                  - demo
                schemas:
                  - public
            sqlite:
              name: Sqlite
              driver: sqlite
              prefer_pdo: true
              directory: "/home/thierry/sqlite"
          default: mysql
          access:
            server: true
          export:
            url: http://symfony.jaxon.loc/exports
            dir: /home/thierry/www/jaxon/frw/symfony-5.3/public/exports
    lib:
      core:
        language:                     "en"
        encoding:                     "UTF-8"
        request:
          uri:                        "ajax"
        prefix:
          class:                      ""
        debug:
          on:                         false
          verbose:                    false
        error:
          handle:                     false
      js:
        lib:
          uri:                        "/jaxon/lib"
        app:
          # uri:
          # dir:
          export:                     false
          minify:                     false
      upload:
        files:
          sql_files:
            dir:                      /home/thierry/workspace/contrib/lagdo/adminer/uploads

      dialogs:
        default:
          modal:                      bootbox
          message:                    noty
          question:                   noty
        pgwjs:
          modal:
            options:
              closeOnEscape:          true
              closeOnBackgroundClick: true
              maxWidth:               600
