    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/js/bootstrap.min.js"></script>

<div id="jaxon-code">
<?php
echo $this->jaxonJs, "\n", $this->jaxonScript, "\n", $this->jaxonCss, "\n";
?>
</div>

</body>
</html>
